class Config:
    PROXY_URL = None
    PROXY_PORT = None
    PROXY_USER = None
    PROXY_PASSWORD = None
    BACKUP_PROXY_URL = None
    BACKUP_PROXY_PORT = None
    BACKUP_PROXY_USER = None
    BACKUP_PROXY_PASSWORD = None
    SPECIAL_PROXY_URL = None  # Proxy 3 for special websites
    SPECIAL_PROXY_PORT = None
    SPECIAL_PROXY_USER = None
    SPECIAL_PROXY_PASSWORD = None
    SPECIAL_BACKUP_PROXY_URL = None  # Proxy 4 for special websites backup
    SPECIAL_BACKUP_PROXY_PORT = None
    SPECIAL_BACKUP_PROXY_USER = None
    SPECIAL_BACKUP_PROXY_PASSWORD = None
    SPECIAL_WEBSITES = []  # Array of websites that must use Proxy 3/4
    DEFAULT_URL = None
    SYNC_DATA = None
    PROFILE = None
    BASE_URL = "http://127.0.0.1:5000/"
    COOKIE_BUCKET_NAME = "espotbrowser-cookies-data"
    VERSION_BUCKET_NAME = "espot-browser-latest-version"
    CLOUDFLARE_ACCESS_KEY = "6cf9c0a917cc03005d53cbd9c29255db"
    CLOUDFLARE_SECRET_KEY = "62aada3122ab29154eb5490204b62ddec5aba43e47d60267fabaee3ae447ea60"
    CLOUDFLARE_ENDPOINT_URL = "https://3e16a6f90ade2025b173edd3439f41f3.r2.cloudflarestorage.com"
    SECRET_KEY = 'QR2vZ7ocC7JkF0b02Kd7a5slN92MYgvd'
    CURRENT_VERSION = 4.1
    CLOUD_VERSION_FILE = "version.json"
    INSTALLER_FILE = "Setup - Espot Browser.exe"
config = Config()